### ISSUE TITLE
Is there any XML schema available for gedcom x ?

### ISSUE THREAD

**Issue by emchateau** [FamilySearch/gedcomx#275]
I've seen the XML serialisation proposition here https://github.com/FamilySearch/gedcomx/blob/master/specifications/xml-format-specification.md

Is there any XML schema already available for gedcom x ?
Thanks a lot

**Comment by stoicflame** [comment]
Yes, actually there is:

http://www.gedcomx.org/gx.xsd

Please note, however, that there _could_ be bugs in the schema. If you report them, we'll look into fixing them, but the schema file is considered non-normative.

**Comment by MystEre84** [comment]
Hi,
I was looking at the XML schema gx.xsd and wanted to report some missing data: in the Person complexType there isn't reference to the XmlAttribute principal and XmlElement field and display.

**Comment by stoicflame** [comment]
Thanks for the report. We'll need to get it updated.
