### ISSUE TITLE
Please add diagrams or flowchart describing the GedcomX file format

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx#277]

**Comment by stoicflame** [comment]
+1. Seems like a reasonable request.

**Comment by hsingh419** [comment]
+1 ditto..

**Comment by FrdNcy** [comment]
please see https://github.com/FamilySearch/gedcomx/blob/master/specifications/support/conceptual-model-graph.pdf

**Comment by weitzhandler** [comment]
Wow! It's so easy to understand it this way!
