### ISSUE TITLE
Time to reboot RDF?

### ISSUE THREAD

**Issue by bplewe** [FamilySearch/gedcomx#279]
This may be a sore subject, but I'm wondering if the spec is now mature enough to redevelop RDF as a serialization option. I'm new, but I heard it was in the conceptual model before, and that didn't go well. 

I have a genealogy project that demands a linked data solution, so if the community doesn't develop a genealogy ontology, I'm going to have to. I don't have 10 years to wait for FHISO to get something done, so GEDCOM X seems like the only game in town. In my experiments so far, it should be doable with the conceptual model as-is (setting up equivalencies to FOAF, BIO, DC, etc.). My early experimental Turtle files have been 30-40% shorter than the XML and JSON files.

Has anyone been working on this? Anyone interested? Can I post the files to this GitHub?

**Comment by stoicflame** [comment]
Sure. Let's do it. Why don't you find some space on [the wiki](https://github.com/FamilySearch/gedcomx/wiki) and let's see what you've got.

**Comment by stoicflame** [comment]
Bump.

I'm ready to start some actual work on this. I'm wondering how to best represent the graph. It seems like RDF/XML is still the prominent representation format for vocabularies, but schema.org uses RDFa.

Any feedback/input?

**Comment by bplewe** [comment]
Ryan, sorry, I backed off a bit from this; it is hard from one day to the next to tell whether semantic web/RDF/linked data is the wave of the future or practically dead :). RDF/XML is almost universally hated, and RDF 1.1 officially supports several serializations; personally, I think TRiG is the most promising (named graphs/quads may be necessary to make this work). RDFa is only useful for attaching attributes to HTML pages. Personally, what I am after is a way to build a linked data front end on FamilySearch Family Tree. Heck, maybe JSON-LD is the way to go?

**Comment by joelcannon** [comment]
Here is the missing link
http://manu.sporny.org/2014/json-ld-origins-2/

and a thumbs up for JSON-LD.

Joel

On Apr 03, 2015, at 04:47 PM, Brandon Plewe <notifications@github.com> wrote:

Ryan, sorry, I backed off a bit from this; it is hard from one day to the next to tell whether semantic web/RDF/linked data is the wave of the future or practically dead :). RDF/XML is almost universally hated, and RDF 1.1 officially supports several serializations; personally, I think TRiG is the most promising (named graphs/quads may be necessary to make this work). RDFa is only useful for attaching attributes to HTML pages. Personally, what I am after is a way to build a linked data front end on FamilySearch Family Tree. Heck, maybe JSON-LD is the way to go?

**Comment by stoicflame** [comment]
I finally got around to publishing some [semantic schema definitions](http://www.gedcomx.org/schemas.html) for the GEDCOM X conceptual model. These definition documents are really just a different encoding of the normative definitions provided by the [GEDCOM X Conceptual Model](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md) specification. The Conceptual Model Specification officially provides the canonical definitions, but these semantic schema documents will make it easier for structure data (e.g. RDFa, Microdata, JSON-LD) processors to use.

I chose to use [RDFa](http://www.w3.org/TR/xhtml-rdfa-primer/) as the encoding for these schema definitions, following the lead of [schema.org](http://schema.org/). I can certainly imagine providing other encodings of the definitions (e.g. Turtle, JSON-LD, RDF/XML), but we'll start with RDFa for now.

One of the nice benefits of this effort is that you don't get a 404 now when you make HTTP requests to the various GEDCOM X data types and controlled vocabulary elements. Instead, the request resolves to one of these semantic schema definitions. For example:

* http://gedcomx.org/v1/Person
* http://gedcomx.org/Male
* http://gedcomx.org/Birth
* http://gedcomx.org/Death
