### ISSUE TITLE
Place reference specification vs example

### ISSUE THREAD

**Issue by eneufeld** [FamilySearch/gedcomx#282]
Hi,
In the model specification of the place reference (https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#conclusion-place-reference) the reference attribute is called descriptionRef, in the file format specifications (https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#conclusion-place-reference) it is also called descriptionRef whereas in the examples it is simply called description.

Could you please clarify?

**Comment by stoicflame** [comment]
Hi.

Thanks for the question.

They're both correct. The name of the _property_ is "descriptionRef". That property name is referenced in both the JSON and XML specs, but each spec chooses to _serialize_ the "descriptionRef" property as "description".

Note the table: the property is "descriptionRef", but the JSON member is "description".

It's a bit weird, but we deliberately kept the two concepts separate; it's useful in other areas of the specs.

**Comment by eneufeld** [comment]
Thank you for pointing this out, I missed the "JSON member" column in the format specificication.
