### ISSUE TITLE
Clarify the use of "analysis" in the JSON example for EvidenceReference Data Type 

### ISSUE THREAD

**Issue by sanojb** [FamilySearch/gedcomx#284]
The example for the EvidenceReference Data Type (https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#37-the-evidencereference-data-type) has an index named "analysis" despite the fact, that neither the general nor the JSON definition has a property of that name. I couldn't find an inheritance notice, so where does that property come from?

**Comment by stoicflame** [comment]
It was a mistake; a copy/paste error. Thanks for pointing it out. Fixed at a979c0.
