### ISSUE TITLE
Inconsistencies in xml-format-specification

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/gedcomx#285]
In the xml-format-specification, I assume that the following are errors:

- Agent
    - `homepage` is listed in the table as being a `gx:ResourceReference` but appears to be a `xsd:string` in the example
    - `openid` is listed in the table as being a `gx:ResourceReference` but appears to be a `xsd:string` in the example

- SourceCitation
    - `textType` is present, but not in the conceptual model; it is also displayed as an attribute of the `value` in the example but listed as an attribute of the `SourceCitation` in the writeup.

- EvidenceReference
    - the example contains an undocumented `gx:analysis` of type `gx:ResourceReference`

**Comment by stoicflame** [comment]
Awesome. Thanks for the report. I'll get it fixed.

**Comment by stoicflame** [comment]
Fixed at c2d5041.

* `homepage` example should imply `ResourceReference` type.
* `openid` example should imply `ResourceReference` type.
* `textType` isn't defined on `SourceCitation` and was removed.
* `analysis` isn't defined on `EvidenceReference` and was removed.
