### ISSUE TITLE
Inconsistencies in json-format-specification

### ISSUE THREAD

**Issue by eneufeld** [FamilySearch/gedcomx#286]
Hi, 
In the json-format-spec there are some inconsistencies:

- Event
  `place` is defined of type Place linking to 'conclusion-place' but there is only a PlaceReference and a PlaceDescription available, I assume it should be a PlaceReference 
- Fact 
   -  `place` is defined of type Place, just as on Event
   - `value` is defined with JSON member `original` but in the example it appears as `value`
- Conclusion
  `notes` is defined with JSON member `note` but in the example it appears as `notes`
- Subject
  - `evidence` is defined as EvidenceReference but is an array in the example and in the conceptional model
  - `media` is defined as SourceReference but is an array in the example and in the conceptional model
  - `identifiers` is defined as Identifier but is an array in the example and in the conceptional model. In JSON it is redefined as being always a set, with the object properties being the `type` and the property value being the `value`. This doesn't fit with the optional and required definitions of the properties as defined in the conceptional model where only the value is required.
-  Person
   link to gender is not working
- Name
   link to NameForm is not working

A very minor issue is, that the anchor names are not consistent, eg : gender-conclusion vs conclusion-date

Cheers,
Eugen

**Comment by eneufeld** [comment]
SourceCitation defines a `textType` which is not defined in the conceptional model

**Comment by stoicflame** [comment]
Awesome. Thanks for the report. We'll clean up those issues.

**Comment by eneufeld** [comment]
One more:
PlaceReference has a property `original` with the JSON member string and the JSON object type OPTIONAL

**Comment by eneufeld** [comment]
Coverage references xml in its description and the properties table has a "XML property" instead of "JSON property" as well as a "XML type"

**Comment by eneufeld** [comment]
about the identifier issue:
The SourceDescription defines an array of Identifier objects for the identifiers property which doesn't work out well with the JSON definition of the Identifier type

**Comment by eneufeld** [comment]
PlaceDescription -> `jurisdiction` JSON object type is gx:ResourceReference

**Comment by eneufeld** [comment]
And one more thing:
the provided example with George Washington is not valid, as the fact defined in the relationship doesn't provide a type which is defined as required

**Comment by eneufeld** [comment]
and the formal date of the relationship is also invalid, it is +01-06-1759 but should be +1759-01-06

**Comment by stoicflame** [comment]
Thanks again. Fixed at 7413f1d.
