### ISSUE TITLE
What happens with compound surnames?

### ISSUE THREAD

**Issue by elboletaire** [FamilySearch/gedcomx#287]
What happens with [compound surnames](https://en.wikipedia.org/wiki/Surname#Compound_surnames)? Although wikipedia says that...

>This custom is not seen in the Hispanic world as being a true compound surname system per se, since it is widely understood that the first surname denotes one's father's family, and the second surname denotes one's mother's family

That's not absolutely true. Currently in Spain one can choose which surname order wants for their son. So this should be a must in a family tree specification.

This may be somehow related to #120, but I'm not sure at all.

**Comment by stoicflame** [comment]
Hi.

Thanks for your interest. Compound surnames should be covered by providing the full text as well as separate name parts. So let's take one of the names mentioned in that wikipedia article you reference, "Luis Telmo Paz y Miño Estrella". We'll use XML for readability and we'll designate "Telmo" as the middle name using a qualifier. We'll also designate "Paz y Miño" as the paternal surname and "Estrella" as the maternal surname using qualifiers.

```xml
<name>
  <nameForm>
    <fullText>Luis Telmo Paz y Miño Estrella</fullText>
    <part type="http://gedcomx.org/Given" value="Luis"/>
    <part type="http://gedcomx.org/Given" value="Telmo">
      <qualifier name="http://gedcomx.org/Middle"/>
    </part>
    <part type="http://gedcomx.org/Surname" value="Paz y Miño">
      <qualifier name="http://gedcomx.org/Patronymic"/>
    </part>
    <part type="http://gedcomx.org/Surname" value="Estrella">
      <qualifier name="http://gedcomx.org/Matronymic"/>
    </part>
  </nameForm>
</name>
```

**Comment by elboletaire** [comment]
Thanks for the clarification! :smile:
