### ISSUE TITLE
What is the timestamp format?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx#290]
The [spec](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#133-basic-data-types) doesn't appear to specify the format, just the contents:

> A "timestamp" refers to an instance of time, including values for year, month, date, hour, minute, second and timezone.

Is that an omission in the docs or does the spec really not specify? I think there ought to be a standard format. Though I'm not aware of any date-time standard other than ISO 8601 that specify the date and time parts so perhaps ISO 8601 is assumed?

**Comment by BruceWhealton** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  futurewavewebdevelopment@gmail.com
    Domain whealton.info has exceeded the max emails per hour (201/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:62054)
	by vps.fwwebdevelopment.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-54f2-bruce=whealton.info@sgmail.github.com>)
	id 1b0XcX-0008G0-LV
	for bruce@whealton.info; Wed, 11 May 2016 13:08:31 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=QkBQmSTUXOt5Qwn+Y+jiQR/67zs=; b=Aeh+WCB1GYCseIHZ
	d+oN64WQf2odi0sEp7utC42F5WejYWW90YFC++AA1Z1KqR9NhXwj+wjgG+tjN3E7
	zJ1WP6xjORX12jABVxPFmM565nr7n4jdt/9ekanOfGZSuD79RdvU+V9qDIy8XmzC
	hGK3nJkCnac94OFealOBwS8BNhs=
Received: by filter0529p1mdw1.sendgrid.net with SMTP id filter0529p1mdw1.18247.573366D990
        2016-05-11 17:07:37.788925288 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 1_tdf1gFQWalPnlCEE3nWw
	for <bruce@whealton.info>; Wed, 11 May 2016 17:07:37.612 +0000 (UTC)
Date: Wed, 11 May 2016 10:07:37 -0700

**Comment by stoicflame** [comment]
The conceptual model doesn't define any formats. The formats are defined by the serialization format specs. XML already has a format defined (`xs:dateTime`). JSON format had to be specified as a number (milliseconds since epoch).
