### ISSUE TITLE
Is ResourceReference.resourceId part of the spec or an extension?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx#300]
It's not listed in [the spec](https://github.com/FamilySearch/gedcomx/blob/d9af3ce7c4f226686a4a77903d5f8298aea3123a/specifications/json-format-specification.md#42-the-resourcereference-data-type) but it's implemented in [gedcomx-java](https://github.com/FamilySearch/gedcomx-java/blob/5b13a7e07bf5ebf93386b94df08e1291b7d737d9/gedcomx-model/src/main/java/org/gedcomx/common/ResourceReference.java#L40) as part of the core spec.

**Comment by stoicflame** [comment]
It's an extension. It should be added to the RS spec.
