### ISSUE TITLE
Maven current version

### ISSUE THREAD

**Issue by dymod** [FamilySearch/gedcomx#304]
Hi,

I am a Java developer and want to start using the your gedcomx reference implementation.  I notice from your page https://repository-gedcom.forge.cloudbees.com/release/org/gedcomx/gedcomx-parent/maven-metadata.xml that the release version is <release>1.0.103.M1</release> but when I try to use this in my maven pom.xml if fails.

When I look on maven central ( https://mvnrepository.com/artifact/org.gedcomx/gedcomx-model/2.2.0 )it lists a <version>2.2.0</version>

Which one should I be using to write my code?

Thanks
Peter Goudman

**Comment by stoicflame** [comment]
We're not using the cloudbees repository anymore. Do I need to update a link to the `metadata.xml` file somewhere?

2.3.0 is the latest version.
