### ISSUE TITLE
Document Identifier type http://gedcomx.org/Persistent

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx#305]
`http://gedcomx.org/Persistent` is in use at FamilySearch but is [missing from the specs](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#known-identifier-types).

**Comment by stoicflame** [comment]
[It's an RS extension.](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md#24-identifier-types)
