### ISSUE TITLE
Date Documentation Discrepancy

### ISSUE THREAD

**Issue by trevoreckersley** [FamilySearch/gedcomx#308]
The date representation [here](https://github.com/FamilySearch/gedcomx/blob/master/specifications/date-format-specification.md#521-representation) does not seem to reflect [this example](https://github.com/FamilySearch/gedcomx/blob/master/specifications/date-format-specification.md#523-examples) or the [PHP format details](http://familysearch.github.io/gedcomx-php/class-Gedcomx.Util.FormalDate.html).

**Comment by stoicflame** [comment]
I think there's something I missing. Can you elaborate?

**Comment by trevoreckersley** [comment]
Sure. If you refer to the first link, you will see that the date format is specified as `±YYYY-MM-DDThh:mm:ss[±hh[:mm]|Z]`; however, the examples in the second link on the same page seem to more accurately match the expression on the PHP page, `(+|-)YYYY[-MM[-DD[Thh[:mm[:ss[(+-)hh[:mm]|Z]]]]]]`.

It seems that either (a) the representation for date listed in the first link should actually be `±YYYY[-MM[-DD[Thh:[mm[:ss[±hh[:mm]|Z]]]]]]`, or (b) some of the date date examples in the second link are invalid and some code changes are needed enforce the representation currently listed in the first link.

**Comment by stoicflame** [comment]
Thanks. Fixed at 0fc6f60.
