### ISSUE TITLE
Add address to place

### ISSUE THREAD

**Issue by MtnBiker** [FamilySearch/gedcomx#316]
I'm not sure how all this works, but having another level for Place makes sense, specifically the street address or possibly the name of the place (St. James Church or City Motel). Having the city as the finest grain doesn't work too well. Yes you can add coordinates, but the app I use has an coordinate finder, but if it can't have an address it's not going to work.

**Comment by stoicflame** [comment]
So the `PlaceDescription` allows for any degree of specificity. Is there a reason you can't just add the address to the place name?

**Comment by MtnBiker** [comment]
That’s what I had started to do. I imagine it will confuse some trying to read it. I just need to get the writer of the app I’m using to support it. I don’t know if he’s using GedcomX or an older version.

So if adding a comma delimited items in Place is OK, you can consider this closed. 

Thanks for responding promptly.

**Comment by stoicflame** [comment]
It's pretty flexible. You can actually separate the description of the address from the description of it's "jurisdiction" (e.g. city) to reduce confusion.
