### ISSUE TITLE
Add 'Intersex' as allowed value for gender/sex

### ISSUE THREAD

**Issue by brylie** [FamilySearch/gedcomx#319]
'Male', 'Female', and 'Unknown' are the current options allowed for the `gender` property (to be called `sex` in GEDCOM X 2.0). However, 'intersex' is also used in some circumstances, so should also be an allowed value.

# Suggestion
Allow 'intersex' as a value for `gender` (1.0) and `sex` (2.0)

Related to #318

**Comment by stoicflame** [comment]
Proposed change has been captured at ed56439. 

We'll leave this open for comments for another week. Unless there are any unanticipated objections, we'll go ahead and merge the proposed change.

**Comment by stoicflame** [comment]
Proposal adopted at 2fd86d4.
