### ISSUE TITLE
How to model groups other than nuclear family?

### ISSUE THREAD

**Issue by brylie** [FamilySearch/gedcomx#322]
There are ongoing discussions on the Gramps mailing list about modelling relationships other than [nuclear family](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#221-known-relationship-types). E.g. when multiple people co-habitate, work together, or other types of group relationships. While it may be possible to express the individual relationships, how can those relationships be connected into a cohesive group unit?

**Comment by stoicflame** [comment]
See #321.
