### ISSUE TITLE
json-format-specification is missing group type of gedcomx type

### ISSUE THREAD

**Issue by eneufeld** [FamilySearch/gedcomx#324]
The https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#43-the-gedcomx-data-type is missing the Group Data Type which is defined in the conceptional model: https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#group

**Comment by stoicflame** [comment]
Thanks. Fixed at 826d723e.
