### ISSUE TITLE
Date specification needs an update.

### ISSUE THREAD

**Issue by dekoza** [FamilySearch/gedcomx#327]
I'm writing a [GEDCOM X toolbox for Python](https://github.com/dekoza/pyGedcomX) (not even Alpha state yet) and found some problems with how Date format is specified.

For example **date-format-specification.md** states:
```
The format for a complete simple date is defined as follows:

±YYYY[-MM[-DD[Thh:[mm[:ss[±hh[:mm]|Z]]]]]]
```
and then in examples we have:
```
+1964-11-14T10-07:00
```
which does not follow the specification.

I had some problems with how `M` is treated in `duration` specs but spotted the T which fixes the parser :wink:

**Comment by dekoza** [comment]
Another example from docs: `+1752-01-18T22:14:3Z` - this does not respect ISO8601:2004 - notation has fixed number of digits, hence it should look like this: `+1752-01-18T22:14:03Z`

**Comment by stoicflame** [comment]
@dekoza thank you so much for your scrutiny. Please continue to point out these errors so they can be corrected.
