### ISSUE TITLE
Page aware reference qualifiers

### ISSUE THREAD

**Issue by berry120** [FamilySearch/gedcomx#332]
I'm looking at a project where I may make reasonably heavy use of interlinking different sources, and what first drew me to this format was the abiltiy to specify "regions" in a source which is fantastic - I haven't found anywhere else that allows that out of the box.

I wonder however if you'd consider making page-aware qualifiers part of the standard (since some types, such as PDF, naturally span multiple pages):
 - `PageRegion` would be great to specify a whole individual page in a document;
 - `PageRectangleRegion` would be great to specify both a page, and a rectangle on that page in the same way as RectangleRegion works currently.

Just for completeness, the specific use case here is digitally referencing a whole bunch of family documents / photos and relating them to each other. I have detailed scans of things such as family photo albums - but I have separate scans of the individual photos in them as well as separate scans of each page (this is important as the pages themselves sometimes contain annotations outside of photos, and I'd like to also preserve the "look" of the original album.) Currently the plan is to relate them in gedcomx by having a PDF of the album at a page level, and then relating the individual images to this PDF by pointing the `componentOf` field in the `SourceDescription` of each individual image to the main PDF - but qualifying the position of those images would then require the page level qualifiers.

(I'm aware that I could just break the standard's recommendation and specify my own qualifiers anyway, but I thought this may be useful in a general case hence the Github issue. Happy to raise a PR if others think this is a good idea.)

**Comment by stoicflame** [comment]
I think those qualifiers sound like a great idea. Go ahead and put together a PR; we'll let it sit for awhile in case anybody wants to comment and then we'll merge it in.

**Comment by berry120** [comment]
I've added both in the PR above. I've tried to remove ambiguity by specifying it's a 1-based integer which doesn't respect any custom page numbering (PDFs can have embedded custom page numbers which I think is fair to ignore in this scenario to avoid confusion) - but happy to make any alternations or additions based on any feedback.

Thanks again for the prompt response!

**Comment by stoicflame** [comment]
I updated the PR with the description of this issue, so I'm going to close this one and invite discussion on the PR.
