### ISSUE TITLE
Example time wrongly converted to 12 hour format

### ISSUE THREAD

**Issue by rgw16** [FamilySearch/gedcomx#335]
https://github.com/FamilySearch/gedcomx/blob/434bc3aade98b2f176149d238eb0f934d1d12e39/specifications/date-format-specification.md?plain=1#L621

A+1980-05-18T18:53Z | minutes | about 4:53 PM [UTC], May 18, 1980

In the example listed above the time 18:53Z converts to 6:53PM [UTC].

**Comment by stoicflame** [comment]
Thanks for the report!
