### ISSUE TITLE
Event/Fact missing Address

### ISSUE THREAD

**Issue by diamondq** [FamilySearch/gedcomx#336]
According to the GEDCOM 5.5.5 [specification](https://www.gedcom.org/specs/GEDCOM555.zip), Events (and Facts/Attributes) have an address associated with them. Gedcomx does not.

### GEDCOM 5.5.5

```
EVENT_DETAIL:=
   n TYPE <EVENT_OR_FACT_CLASSIFICATION>
   n DATE <DATE_VALUE>
   n <<PLACE_STRUCTURE>>
   n <<ADDRESS_STRUCTURE>>
   n AGNC <RESPONSIBLE_AGENCY>
   n RELI <RELIGIOUS_AFFILIATION>
   n CAUS <CAUSE_OF_EVENT>
   n <<NOTE_STRUCTURE>>
   n <<SOURCE_CITATION>>
   n <<MULTIMEDIA_LINK>>
```

`EVENT_DETAIL` is used as the basis of events (via `INDIVIDUAL_EVENT_STRUCTURE` and `FAMILY_EVENT_STRUCTURE`) and facts/attributes (via `INDIVIDUAL_ATTRIBUTE_STRUCTURE`).

`EVENT_DETAIL` contains a `PLACE` and an `ADDRESS`.

### Gedcomx

As of reporting, Events ( [Defined here](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#event) ) and Facts ( [Defined here](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#3-fact-conclusion) ) only have a PLACE reference.

The GEDCOM5 to GEDCOMX conversion library acknowledges that it's missing.

[FactMapper.java:240](https://github.com/FamilySearch/gedcom5-conversion/blob/e494d3c1d635a57ed32964e393dc676eb413ae0b/src/main/java/org/gedcomx/conversion/gedcom/dq55/FactMapper.java#L240)

### Suggestion
As there is already an Address Data type, it should be able to be added to the Events and Facts Data Type as an OPTIONAL element without too much impact.

**Comment by stoicflame** [comment]
Hello @diamondq! Thanks for the enhancement request.

We believe that adding `Address` as a property to the `Event` and/or `Fact` type would be redundant. The `PlaceReference` has plenty of specificity for mapping an address. At a bare minimum you could just put the address in the `original` property, but you could also map the address to multiple levels of a `PlaceDescription` object (including lat/long geo coordinates) and reference the `PlaceDescription` with the `PlaceReference`.

So with respect and appreciation we're going to decline this suggestion.
